export const langOptions = [
  { label: '自动检测', value: 'auto' },
  // 中文相关
  { label: '中文', value: 'zh' },
  { label: '中文(简体)', value: 'zh' },
  { label: '中文(繁体)', value: 'cht' },
  { label: '中文(文言文)', value: 'wyw' },
  { label: '中文(粤语)', value: 'yue' },
  // A开头
  { label: '阿拉伯语', value: 'ara' },
  { label: '爱尔兰语', value: 'gle' },
  { label: '奥克语', value: 'oci' },
  { label: '阿尔巴尼亚语', value: 'alb' },
  { label: '阿尔及利亚阿拉伯语', value: 'arq' },
  { label: '阿肯语', value: 'aka' },
  { label: '阿拉贡语', value: 'arg' },
  { label: '阿姆哈拉语', value: 'amh' },
  { label: '阿萨姆语', value: 'asm' },
  { label: '艾马拉语', value: 'aym' },
  { label: '阿塞拜疆语', value: 'aze' },
  { label: '阿斯图里亚斯语', value: 'ast' },
  { label: '奥塞梯语', value: 'oss' },
  { label: '爱沙尼亚语', value: 'est' },
  { label: '奥杰布瓦语', value: 'oji' },
  { label: '奥里亚语', value: 'ori' },
  { label: '奥罗莫语', value: 'orm' },
  // B开头
  { label: '波兰语', value: 'pl' },
  { label: '波斯语', value: 'per' },
  { label: '布列塔尼语', value: 'bre' },
  { label: '巴什基尔语', value: 'bak' },
  { label: '巴斯克语', value: 'baq' },
  { label: '巴西葡萄牙语', value: 'pot' },
  { label: '白俄罗斯语', value: 'bel' },
  { label: '柏柏尔语', value: 'ber' },
  { label: '邦板牙语', value: 'pam' },
  { label: '保加利亚语', value: 'bul' },
  { label: '北方萨米语', value: 'sme' },
  { label: '北索托语', value: 'ped' },
  { label: '本巴语', value: 'bem' },
  { label: '比林语', value: 'bli' },
  { label: '比斯拉马语', value: 'bis' },
  { label: '俾路支语', value: 'bal' },
  { label: '冰岛语', value: 'ice' },
  { label: '波斯尼亚语', value: 'bos' },
  { label: '博杰普尔语', value: 'bho' },
  // C开头
  { label: '楚瓦什语', value: 'chv' },
  { label: '聪加语', value: 'tso' },
  // D开头
  { label: '丹麦语', value: 'dan' },
  { label: '德语', value: 'de' },
  { label: '鞑靼语', value: 'tat' },
  { label: '掸语', value: 'sha' },
  { label: '德顿语', value: 'tet' },
  { label: '迪维希语', value: 'div' },
  { label: '低地德语', value: 'log' },
  // E开头
  { label: '俄语', value: 'ru' },
  // F开头
  { label: '法语', value: 'fra' },
  { label: '菲律宾语', value: 'fil' },
  { label: '芬兰语', value: 'fin' },
  { label: '梵语', value: 'san' },
  { label: '弗留利语', value: 'fri' },
  { label: '富拉尼语', value: 'ful' },
  { label: '法罗语', value: 'fao' },
  // G开头
  { label: '盖尔语', value: 'gla' },
  { label: '刚果语', value: 'kon' },
  { label: '高地索布语', value: 'ups' },
  { label: '高棉语', value: 'hkm' },
  { label: '格陵兰语', value: 'kal' },
  { label: '格鲁吉亚语', value: 'geo' },
  { label: '古吉拉特语', value: 'guj' },
  { label: '古希腊语', value: 'gra' },
  { label: '古英语', value: 'eno' },
  { label: '瓜拉尼语', value: 'grn' },
  // H开头
  { label: '韩语', value: 'kor' },
  { label: '荷兰语', value: 'nl' },
  { label: '胡帕语', value: 'hup' },
  { label: '哈卡钦语', value: 'hak' },
  { label: '海地语', value: 'ht' },
  { label: '黑山语', value: 'mot' },
  { label: '豪萨语', value: 'hau' },
  // J开头
  { label: '吉尔吉斯语', value: 'kir' },
  { label: '加利西亚语', value: 'glg' },
  { label: '加拿大法语', value: 'frn' },
  { label: '加泰罗尼亚语', value: 'cat' },
  { label: '捷克语', value: 'cs' },
  // K开头
  { label: '卡拜尔语', value: 'kab' },
  { label: '卡纳达语', value: 'kan' },
  { label: '卡努里语', value: 'kau' },
  { label: '卡舒比语', value: 'kah' },
  { label: '康瓦尔语', value: 'cor' },
  { label: '科萨语', value: 'xho' },
  { label: '科西嘉语', value: 'cos' },
  { label: '克里克语', value: 'cre' },
  { label: '克里米亚鞑靼语', value: 'cri' },
  { label: '克林贡语', value: 'kli' },
  { label: '克罗地亚语', value: 'hrv' },
  { label: '克丘亚语', value: 'que' },
  { label: '克什米尔语', value: 'kas' },
  { label: '孔卡尼语', value: 'kok' },
  { label: '库尔德语', value: 'kur' },
  // L开头
  { label: '拉丁语', value: 'lat' },
  { label: '老挝语', value: 'lao' },
  { label: '罗马尼亚语', value: 'rom' },
  { label: '拉特加莱语', value: 'lag' },
  { label: '拉脱维亚语', value: 'lav' },
  { label: '林堡语', value: 'lim' },
  { label: '林加拉语', value: 'lin' },
  { label: '卢干达语', value: 'lug' },
  { label: '卢森堡语', value: 'ltz' },
  { label: '卢森尼亚语', value: 'ruy' },
  { label: '卢旺达语', value: 'kin' },
  { label: '立陶宛语', value: 'lit' },
  { label: '罗曼什语', value: 'roh' },
  { label: '罗姆语', value: 'ro' },
  { label: '逻辑语', value: 'loj' },
  // M开头
  { label: '马来语', value: 'may' },
  { label: '缅甸语', value: 'bur' },
  { label: '马拉地语', value: 'mar' },
  { label: '马拉加斯语', value: 'mg' },
  { label: '马拉雅拉姆语', value: 'mal' },
  { label: '马其顿语', value: 'mac' },
  { label: '马绍尔语', value: 'mah' },
  { label: '迈蒂利语', value: 'mai' },
  { label: '曼克斯语', value: 'glv' },
  { label: '毛里求斯克里奥尔语', value: 'mau' },
  { label: '毛利语', value: 'mao' },
  { label: '孟加拉语', value: 'ben' },
  { label: '马耳他语', value: 'mlt' },
  { label: '苗语', value: 'hmn' },
  // N开头
  { label: '挪威语', value: 'nor' },
  { label: '那不勒斯语', value: 'nea' },
  { label: '南恩德贝莱语', value: 'nbl' },
  { label: '南非荷兰语', value: 'afr' },
  { label: '南索托语', value: 'sot' },
  { label: '尼泊尔语', value: 'nep' },
  // P开头
  { label: '葡萄牙语', value: 'pt' },
  { label: '旁遮普语', value: 'pan' },
  { label: '帕皮阿门托语', value: 'pap' },
  { label: '普什图语', value: 'pus' },
  // Q开头
  { label: '齐切瓦语', value: 'nya' },
  { label: '契维语', value: 'twi' },
  { label: '切罗基语', value: 'chr' },
  // R开头
  { label: '日语', value: 'jp' },
  { label: '瑞典语', value: 'swe' },
  // S开头
  { label: '萨丁尼亚语', value: 'srd' },
  { label: '萨摩亚语', value: 'sm' },
  { label: '塞尔维亚-克罗地亚语', value: 'sec' },
  { label: '塞尔维亚语', value: 'srp' },
  { label: '桑海语', value: 'sol' },
  { label: '僧伽罗语', value: 'sin' },
  { label: '世界语', value: 'epo' },
  { label: '书面挪威语', value: 'nob' },
  { label: '斯洛伐克语', value: 'sk' },
  { label: '斯洛文尼亚语', value: 'slo' },
  { label: '斯瓦希里语', value: 'swa' },
  { label: '塞尔维亚语（西里尔）', value: 'src' },
  { label: '索马里语', value: 'som' },
  { label: '苏格兰语', value: 'sco' },
  // T开头
  { label: '泰语', value: 'th' },
  { label: '土耳其语', value: 'tr' },
  { label: '塔吉克语', value: 'tgk' },
  { label: '泰米尔语', value: 'tam' },
  { label: '他加禄语', value: 'tgl' },
  { label: '提格利尼亚语', value: 'tir' },
  { label: '泰卢固语', value: 'tel' },
  { label: '突尼斯阿拉伯语', value: 'tua' },
  { label: '土库曼语', value: 'tuk' },
  // W开头
  { label: '乌克兰语', value: 'ukr' },
  { label: '瓦隆语', value: 'wln' },
  { label: '威尔士语', value: 'wel' },
  { label: '文达语', value: 'ven' },
  { label: '沃洛夫语', value: 'wol' },
  { label: '乌尔都语', value: 'urd' },
  // X开头
  { label: '西班牙语', value: 'spa' },
  { label: '希伯来语', value: 'heb' },
  { label: '希腊语', value: 'el' },
  { label: '匈牙利语', value: 'hu' },
  { label: '西弗里斯语', value: 'fry' },
  { label: '西里西亚语', value: 'sil' },
  { label: '希利盖农语', value: 'hil' },
  { label: '下索布语', value: 'los' },
  { label: '夏威夷语', value: 'haw' },
  { label: '新挪威语', value: 'nno' },
  { label: '西非书面语', value: 'nqo' },
  { label: '信德语', value: 'snd' },
  { label: '修纳语', value: 'sna' },
  { label: '宿务语', value: 'ceb' },
  { label: '叙利亚语', value: 'syr' },
  { label: '巽他语', value: 'sun' },
  // Y开头
  { label: '英语', value: 'en' },
  { label: '印地语', value: 'hi' },
  { label: '印尼语', value: 'id' },
  { label: '意大利语', value: 'it' },
  { label: '越南语', value: 'vie' },
  { label: '意第绪语', value: 'yid' },
  { label: '因特语', value: 'ina' },
  { label: '亚齐语', value: 'ach' },
  { label: '印古什语', value: 'ing' },
  { label: '伊博语', value: 'ibo' },
  { label: '伊多语', value: 'ido' },
  { label: '约鲁巴语', value: 'yor' },
  { label: '亚美尼亚语', value: 'arm' },
  { label: '伊努克提图特语', value: 'iku' },
  // Z开头
  { label: '扎扎其语', value: 'zaz' },
  { label: '中古法语', value: 'frm' },
  { label: '祖鲁语', value: 'zul' },
  { label: '爪哇语', value: 'jav' }
]

export const lang = {
  'auto': '自动检测',
  // 中文相关
  'zh': '中文(简体)',
  'cht': '中文(繁体)',
  'wyw': '中文(文言文)',
  'yue': '中文(粤语)',
  // 其他语言
  'ara': '阿拉伯语',
  'gle': '爱尔兰语',
  'oci': '奥克语',
  'alb': '阿尔巴尼亚语',
  'arq': '阿尔及利亚阿拉伯语',
  'aka': '阿肯语',
  'arg': '阿拉贡语',
  'amh': '阿姆哈拉语',
  'asm': '阿萨姆语',
  'aym': '艾马拉语',
  'aze': '阿塞拜疆语',
  'ast': '阿斯图里亚斯语',
  'oss': '奥塞梯语',
  'est': '爱沙尼亚语',
  'oji': '奥杰布瓦语',
  'ori': '奥里亚语',
  'orm': '奥罗莫语',
  'pl': '波兰语',
  'per': '波斯语',
  'bre': '布列塔尼语',
  'bak': '巴什基尔语',
  'baq': '巴斯克语',
  'pot': '巴西葡萄牙语',
  'bel': '白俄罗斯语',
  'ber': '柏柏尔语',
  'pam': '邦板牙语',
  'bul': '保加利亚语',
  'sme': '北方萨米语',
  'ped': '北索托语',
  'bem': '本巴语',
  'bli': '比林语',
  'bis': '比斯拉马语',
  'bal': '俾路支语',
  'ice': '冰岛语',
  'bos': '波斯尼亚语',
  'bho': '博杰普尔语',
  'chv': '楚瓦什语',
  'tso': '聪加语',
  'dan': '丹麦语',
  'de': '德语',
  'tat': '鞑靼语',
  'sha': '掸语',
  'tet': '德顿语',
  'div': '迪维希语',
  'log': '低地德语',
  'ru': '俄语',
  'fra': '法语',
  'fil': '菲律宾语',
  'fin': '芬兰语',
  'san': '梵语',
  'fri': '弗留利语',
  'ful': '富拉尼语',
  'fao': '法罗语',
  'gla': '盖尔语',
  'kon': '刚果语',
  'ups': '高地索布语',
  'hkm': '高棉语',
  'kal': '格陵兰语',
  'geo': '格鲁吉亚语',
  'guj': '古吉拉特语',
  'gra': '古希腊语',
  'eno': '古英语',
  'grn': '瓜拉尼语',
  'kor': '韩语',
  'nl': '荷兰语',
  'hup': '胡帕语',
  'hak': '哈卡钦语',
  'ht': '海地语',
  'mot': '黑山语',
  'hau': '豪萨语',
  'kir': '吉尔吉斯语',
  'glg': '加利西亚语',
  'frn': '加拿大法语',
  'cat': '加泰罗尼亚语',
  'cs': '捷克语',
  'kab': '卡拜尔语',
  'kan': '卡纳达语',
  'kau': '卡努里语',
  'kah': '卡舒比语',
  'cor': '康瓦尔语',
  'xho': '科萨语',
  'cos': '科西嘉语',
  'cre': '克里克语',
  'cri': '克里米亚鞑靼语',
  'kli': '克林贡语',
  'hrv': '克罗地亚语',
  'que': '克丘亚语',
  'kas': '克什米尔语',
  'kok': '孔卡尼语',
  'kur': '库尔德语',
  'lat': '拉丁语',
  'lao': '老挝语',
  'rom': '罗马尼亚语',
  'lag': '拉特加莱语',
  'lav': '拉脱维亚语',
  'lim': '林堡语',
  'lin': '林加拉语',
  'lug': '卢干达语',
  'ltz': '卢森堡语',
  'ruy': '卢森尼亚语',
  'kin': '卢旺达语',
  'lit': '立陶宛语',
  'roh': '罗曼什语',
  'ro': '罗姆语',
  'loj': '逻辑语',
  'may': '马来语',
  'bur': '缅甸语',
  'mar': '马拉地语',
  'mg': '马拉加斯语',
  'mal': '马拉雅拉姆语',
  'mac': '马其顿语',
  'mah': '马绍尔语',
  'mai': '迈蒂利语',
  'glv': '曼克斯语',
  'mau': '毛里求斯克里奥尔语',
  'mao': '毛利语',
  'ben': '孟加拉语',
  'mlt': '马耳他语',
  'hmn': '苗语',
  'nor': '挪威语',
  'nea': '那不勒斯语',
  'nbl': '南恩德贝莱语',
  'afr': '南非荷兰语',
  'sot': '南索托语',
  'nep': '尼泊尔语',
  'pt': '葡萄牙语',
  'pan': '旁遮普语',
  'pap': '帕皮阿门托语',
  'pus': '普什图语',
  'nya': '齐切瓦语',
  'twi': '契维语',
  'chr': '切罗基语',
  'jp': '日语',
  'swe': '瑞典语',
  'srd': '萨丁尼亚语',
  'sm': '萨摩亚语',
  'sec': '塞尔维亚-克罗地亚语',
  'srp': '塞尔维亚语',
  'sol': '桑海语',
  'sin': '僧伽罗语',
  'epo': '世界语',
  'nob': '书面挪威语',
  'sk': '斯洛伐克语',
  'slo': '斯洛文尼亚语',
  'swa': '斯瓦希里语',
  'src': '塞尔维亚语（西里尔）',
  'som': '索马里语',
  'sco': '苏格兰语',
  'th': '泰语',
  'tr': '土耳其语',
  'tgk': '塔吉克语',
  'tam': '泰米尔语',
  'tgl': '他加禄语',
  'tir': '提格利尼亚语',
  'tel': '泰卢固语',
  'tua': '突尼斯阿拉伯语',
  'tuk': '土库曼语',
  'ukr': '乌克兰语',
  'wln': '瓦隆语',
  'wel': '威尔士语',
  'ven': '文达语',
  'wol': '沃洛夫语',
  'urd': '乌尔都语',
  'spa': '西班牙语',
  'heb': '希伯来语',
  'el': '希腊语',
  'hu': '匈牙利语',
  'fry': '西弗里斯语',
  'sil': '西里西亚语',
  'hil': '希利盖农语',
  'los': '下索布语',
  'haw': '夏威夷语',
  'nno': '新挪威语',
  'nqo': '西非书面语',
  'snd': '信德语',
  'sna': '修纳语',
  'ceb': '宿务语',
  'syr': '叙利亚语',
  'sun': '巽他语',
  'en': '英语',
  'hi': '印地语',
  'id': '印尼语',
  'it': '意大利语',
  'vie': '越南语',
  'yid': '意第绪语',
  'ina': '因特语',
  'ach': '亚齐语',
  'ing': '印古什语',
  'ibo': '伊博语',
  'ido': '伊多语',
  'yor': '约鲁巴语',
  'arm': '亚美尼亚语',
  'iku': '伊努克提图特语',
  'zaz': '扎扎其语',
  'frm': '中古法语',
  'zul': '祖鲁语',
  'jav': '爪哇语'
}